### ISSUE TITLE
如何热更实体中new的对象类

### ISSUE THREAD

**Issue by Leovany** [ahffffffff/kbengine_hotfix#1]
十分感谢大佬的分享，按着文档提示操作，遇到了几个问题，过来请教一下
1.  onTimer 中的定时器，似乎一起动就一直在回调，这个是否有性能的问题？
2.  在实体类中new了类，实体更新了，但new的类没有更新，是我哪里写错了吗？

Account new MoneyPlayerData类
`
class Account(KBEngine.Proxy,Hotfix.Hotfix):

	def __init__(self):
		KBEngine.Proxy.__init__(self)
		Hotfix.Hotfix.__init__(self)

		self.moneyPlayerData =  playerData.MoneyPlayerData.MoneyPlayerData()
`

MoneyPlayerData 继承 BasePlayerData
`
class MoneyPlayerData(playerData.BasePlayerData.BasePlayerData,Hotfix.Hotfix):

	def initData(self,player):
		# 基类初始化
		super(MoneyPlayerData,self).initData(player)
		Hotfix.Hotfix.__init__(self)
`

BasePlayerData
`
class BasePlayerData():

	# 默认初始化
	def initData(self,player):
		#My_WARNING_MSG("BasePlayerData::__init__");
		self.player = player;

	# 初始化玩家数据
	def initFirstData(self):
		pass

	# 重置玩家数据
	def resetData(self):
		pass

	# 下发之前校验数据
	def checkPlayerData(self):
		pass

	# 初始下发参数
	def getInitParams(self,dict):
		return dict

	# 上传数据
	def uploadData(self,dict):
		pass

	# 刷新每日数据
	def refreshDayData(self):
		pass

	def getPlayerID(self):
		return self.player.playerID;
`

**Comment by justquickdoit** [comment]
onTimer 中的定时器，似乎一起动就一直在回调，这个是否有性能的问题？
--------------------------------------------------------------------------------------
这个消耗九牛一毛了，定时回调只有检查版本不一致时才热更。而每个进程调用一个定时器完全可以忽略不计算；

在实体类中new了类，实体更新了，但new的类没有更新，是我哪里写错了吗？
--------------------------------------------------------------------------------------
要热更的类是派生了子类的，那不仅要同时也需要将子类发起下热更；
class A:
class B(A):

如果修改了 class A，需要热更， 那么需要将 class A发起热更，在之后再将 class B发起热更（就算B没有作任何改动）；

**Comment by Leovany** [comment]
> ## 在实体类中new了类，实体更新了，但new的类没有更新，是我哪里写错了吗？
> 要热更的类是派生了子类的，那不仅要同时也需要将子类发起下热更；
> class A:
> class B(A):
> 
> 如果修改了 class A，需要热更， 那么需要将 class A发起热更，在之后再将 class B发起热更（就算B没有作任何改动）；

1. 有三个类

 class A:
 class B(A):

class Account(KBEngine.Proxy,Hotfix.Hotfix):
    def __init__(self):
		KBEngine.Proxy.__init__(self)
		Hotfix.Hotfix.__init__(self)
               self.b = B()

2. 修改了B类代码

3. 进行热更

`
hot = KBEngine.globalData['Hotfix_Ent'] 

hot.B_Hotfix_Hotfile(1, ['Account'])  

hot.B_Hotfix_Hotfile(1, ['A'])  

hot.B_Hotfix_Hotfile(1, ['B']) 
`

十分感谢大佬的回复，我尝试按上面方式热更，Account 可以正常更新，但B 类还是旧内容
请教下，我这边是什么问题？

**Comment by justquickdoit** [comment]
A和B类的 Hotfix_Update() 调用了吗？

参考 Account类的 Hotfix_Update()调用

**Comment by Leovany** [comment]
A 和 B 类不是实体，是挂在Account 上的管理对象，这个要怎么调用？

按下面这样写可以吗？

1. 定义
```
class A(Hotfix.Hotfix)：
     def __init__(self):
          Hotfix.Hotfix.__init__(self)

class B(A)：
   def __init__(self):
         super(B,self).__init__()
```
2. 调用
```
class Account(KBEngine.Proxy,Hotfix.Hotfix):
      def __init__(self):
		KBEngine.Proxy.__init__(self)
		Hotfix.Hotfix.__init__(self)
                self.b = B()

     def onTimer(self, timerHandle, userData):
           if userData == Hotfix.TUArg_Hotfix:
               # Account 调用
               self.Hotfix_Update()
               # B 调用
               self.b.Hotfix_Update()
```

**Comment by justquickdoit** [comment]
可以的。 非实体得依赖外部的调用。

**Comment by Leovany** [comment]
哇，大佬可以了，十分感谢 ！！！

PS: 其他人可能也会遇到我这个问题，建议把这块加到 README 里

**Comment by justquickdoit** [comment]
好的。有issues
